#!/bin/bash

while getopts b:p:a: flag;
do
  case "${flag}" in
    b) browser=${OPTARG};;
    p)
      case ${OPTARG} in
        core)
          fullPlatformName="CorePlatform";;
        website)
          fullPlatformName="WebsitePlatform";;
        creator)
          fullPlatformName="CreatorPlatform";;
        classmate)
          fullPlatformName="ClassmatePlatform";;
        commerce)
          fullPlatformName="CommercePlatform";;
      esac
      platform+=" --tests *$fullPlatformName*";;
    a) activeProfile=${OPTARG};;
  esac
done

if [ -z $platform ];
  then platform=" --tests *TestAll*"
fi

if [ -z $browser ];
  then browser=chrome
fi

export browser=$browser;
export activeProfile=$activeProfile;

./gradlew clean test $platform