#!/bin/bash

while getopts b:p:a: flag;
do
  case "${flag}" in
    b) browser=${OPTARG};;
    p) platform+=" --tests *${OPTARG}*";;
    a) activeProfile=${OPTARG};;
  esac
done

if [ -z $platform ];
  then platform=" --tests *TestAll*"
fi

if [ -z $browser ];
  then browser=chrome
fi

export browser=$browser;
export activeProfile=$activeProfile;

./gradlew clean test $platform