package net.class101.automateduitest;

import static com.codeborne.selenide.Selectors.byClassName;
import static com.codeborne.selenide.Selectors.byTagName;
import static com.codeborne.selenide.Selectors.byXpath;
import static com.codeborne.selenide.Selectors.withText;

import org.openqa.selenium.By;

public final class Constants {
    public static final String STAGING_PLUS_HOME_URL = "https://staging.class101.net/plus/ko";
    public static final String STAGING_PLUS_MY_PAGE_URL = "https://staging.class101.net/plus/ko/mypage";
    public static final String CLASS101_USER_ID = "referral_1@101.inc";
    public static final String CLASS101_PASSWORD = "class101!";
    public static final String CLASS101_EMAIL_INPUT_FIELD = "input[name='email']";
    public static final String CLASS101_PASSWORD_INPUT_FIELD = "input[name='password']";
    public static final String LOGIN_PAGE_LOGIN_BUTTON = "button[type='submit']";
    public static final String USER_NAVIGATION_PROFILE_IMG = "img[alt='profile']";
    public static final By USER_NAVIGATION_LOGIN_BUTTON = withText("로그인");
    public static final By LOGIN_PAGE_ALL_LOGIN_BUTTON = withText("다른 방법으로 로그인");
    public static final By LOGIN_PAGE_NAVER_BUTTON = withText("네이버");
    public static final By LOGIN_PAGE_FACEBOOK_BUTTON = withText("페이스북");
    public static final By MY_PAGE_LOGOUT_BUTTON = withText("로그아웃");
    public static final String FACEBOOK_EMAIL_INPUT_FIELD = "input[id='email']";
    public static final String FACEBOOK_PASSWORD_INPUT_FIELD = "input[name='pass']";
    public static final String FACEBOOK_LOGIN_BUTTON = "button[type='submit']";
    public static final String FACEBOOK_USER_ID = "steven@101.inc";
    public static final String FACEBOOK_PASSWORD = "class101!";
    public static final String NAVER_ID_INPUT_FIELD = "input[id='id']";
    public static final String NAVER_PASSWORD_INPUT_FIELD = "input[id='pw']";
    public static final String NAVER_LOGIN_BUTTON = "button[class='btn_login']";
    public static final String NAVER_USER_ID = "candy6731";
    public static final String NAVER_PASSWORD = "class101!";
    public static final By TRENDING_CLASS_SECTION = withText("실시간 인기 클래스");
    public static final By FIRST_SAVE_BUTTON_ON_TRENDING_NOW = byXpath("(//section[contains(.,'실시간 인기 클래스')]/div[3]/div/div/div/div/div/button)[1]");
    public static final By SAVED_CLASSES_SECTION_TITLE = byXpath("//h4[contains(.,'찜한 클래스')]");
    public static final By RECOMMENDED_CLASS_SECTION = withText("추천 클래스");
//    public static final By FIRST_ITEM_OF_COOKING_SECTION = byXpath("//section[contains(.,'요리 클래스')]/div[3]/div/div/div/div");
//    public static final By FIRST_ITEM_OF_TRENDING_NOW = byXpath("//section[contains(.,'인기 클래스')]/div[3]/div/div/div/div");
//    public static final By USER_NAVIGATION_LOGO = byXpath("//a[@href='/plus/ko']");
//    public static final By FIRST_RECOMMENDATION_CLASS_TITLE = byXpath("//section[contains(.,'추천 클래스')]/div[3]/div/div/div/div/div/div/a/div[2]/span");
    public static final By FIRST_CURATION_ITEM = byXpath("//img[@alt='desktop-hero-banner']");
    public static final By CLASS101_PLUS_SUBSCRIBE_BUTTON = withText("시작하기");
    public static final By SUBSCRIPTION_PLAN_TITLE = withText("구독 상품");
    public static final By RECOMMENDED_CATEGORY_SECTION = withText("관심 클래스를 발견하지 못하셨나요?");
    public static final By ENGLISH_CATEGORY_BUTTON = byXpath("//button[contains(.,'영어')]");
    public static final String MY_CLASS_USER_ID = "sbtestc422@101.inc";
    public static final String MY_CLASS_PASSWORD = "test001!";
    public static final By MY_CLASS_SECTION = byXpath("//h4[contains(.,'내 클래스')]");
    public static final By SEARCH_BAR = byXpath("//p[contains(.,'찾기')]");
    public static final By SEARCH_PANEL_TITLE = withText("지금 인기있는");
    public static final By SEARCH_BAR_INPUT_AFTER_CLICK = byTagName("input");
    public static final By SEARCH_RESULT_CRAFTS_CATEGORY = byXpath("//button[contains(.,'공예')]");
    public static final By SUBCATEGORY_ENGLISH_COMMUNICATION = byXpath("//a[@href='/plus/ko/categories/6220895c9dede0214b0783e4']");
    public static final String SUBCATEGORY_ID_ENGLISH_COMMUNICATION = "6220895c9dede0214b0783e4";
    public static final By CLASS_INTRODUCTION_TAB_ON_PDP = byXpath("//span[contains(.,'클래스 소개')]");
    public static final By CREATOR_INTRODUCTION_TAB_ON_PDP = byXpath("//span[contains(.,'크리에이터')]");
    public static final By MY_PAGE_CASH_TAB = byXpath("//a[contains(@href,'cash')]");
    public static final By MY_PAGE_SUBSCRIPTION_STATUS_NON = byXpath("//a[contains(@href,'subscription') and contains(.,'구독하기')]");
    public static final By MY_PAGE_SUBSCRIPTION_STATUS_SUBSCRIBED = byXpath("//a[contains(@href,'subscription') and contains(.,'구독 중')]");
    public static final By MY_PAGE_ORDER_TAB = byXpath("//a[contains(@href,'orders')]");
    public static final By MY_PAGE_REFERRAL_TAB = byXpath("//a[contains(@href,'classmate-referral')]");
    public static final By MY_PAGE_CREATOR_CENTER_TAB = byXpath("//button[contains(.,'크리에이터 센터')]");
    public static final By MY_PAGE_FAQ_TAB = byXpath("//a[contains(@href,'intercom.help/class101faq')]");
    public static final By MY_PAGE_ENQUIRY_TAB = byXpath("//button[contains(.,'1:1 문의')]");
    public static final By MY_PAGE_SETTING_TAB = byXpath("//a[contains(@href,'setting')]");
    public static final By CHANNEL_TALK_MODAL = byClassName("ch-desk-messenger");
    public static final By SETTING_SERVICE_REGION_BUTTON = withText("지역 설정");
    public static final By SERVICE_REGION_US_BUTTON = byXpath("//p[contains(.,'United States / English')]");
    public static final By SERVICE_REGION_JP_BUTTON = byXpath("//p[contains(.,'日本 / 日本語')]");
    public static final By PLAY_BUTTON_ON_PDP = byXpath("//button[contains(.,'재생하기')]");
    public static final By VIDEO_PLAYING = byXpath("//div[contains(@class,'playing')]");
    public static final String CREATOR_CENTER_STAGING_URL = "https://staging-creator.class101.net/center/products";
    public static final String CREATOR_USER_ID = "steven97@101.inc";
    public static final String CREATOR_PASSWORD = "class101!";
    public static final By CREATE_PRODUCT_BUTTON = byXpath("//a[@href='/center/products/add']");
    public static final By CREATE_CLASS_BUTTON = byXpath("(//button[contains(.,'만들기')])[1]");
    public static final By CREATE_CLASS_PAGE_CATEGORY_SECTION = byXpath("//p[text()='카테고리']");
    public static final By FIRST_CATEGORY_SELECTOR = byXpath("(//form[contains(.,'분야를 선택해주세요')]//select)[1]");
    public static final By SECOND_CATEGORY_SELECTOR = byXpath("(//form[contains(.,'분야를 선택해주세요')]//select)[2]");
    public static final By THIRD_CATEGORY_SELECTOR = byXpath("(//form[contains(.,'분야를 선택해주세요')]//select)[3]");
    public static final By FOURTH_CATEGORY_SELECTOR = byXpath("(//form[contains(.,'분야를 선택해주세요')]//select)[4]");
    public static final By VIDEO_PLAY_SPEED_BUTTON = byXpath("(//div[div[contains(@class,'video')]]//span)[14]");
    public static final By VIDEO_SETTING_BUTTON = byXpath("(//div[div[contains(@class,'video')]]//span)[15]");
    public static final By VIDEO_SETTING_QUALITY_BUTTON = byXpath("//div[div[p[text() = '화질']]]");
    public static final By VIDEO_SETTING_QUALITY_CURRENT_VALUE = byXpath("//div[div[p[text() = '화질']]]//button//span[contains(.,'p')]");
    public static final By VIDEO_SETTING_AUTO_PLAY_BUTTON = byXpath("//div[div[p[text() = '자동 재생']]]");
    public static final By VIDEO_SETTING_AUTO_PLAY_CURRENT_VALUE = byXpath("(//div[div[p[text() = '자동 재생']]]//button//span)[2]");
    public static final By VIDEO_SETTING_FIRST_RADIO_OPTION_NOT_CHECKED = byXpath("//label[input[@type='radio' and not(@checked)]]");
    public static final By UNCHECKED_AUTO_PLAY_OPTION_TEXT = By.xpath("//div[label[input[@type='radio' and not(@checked)]]]//p");
}
